export enum LOCAL_STORAGE_KEYS {
  WEEKLY_STREAK = "WEEKLY_STREAK",
  USER = "USER",
  RATE_PROMPTED = "RATE_PROMPTED",
  LAST_OPENED = "LAST_OPENED",
  DAILY_DATA = "DAILY_DATA",
  INTAKE_GOAL = "INTAKE_GOAL",
  WEIGHT_HISTORY = "WEIGHT_HISTORY",
  HAS_SEEN_ONBOARDING = "HAS_SEEN_ONBOARDING",
  TODAYS_FOOD_ENTRIES = "TODAYS_FOOD_ENTRIES",
  UNIT_PREFERENCE = "UNIT_PREFERENCE",
}
